import type { Bill, Goal, OverviewData, Transaction } from "./types"

export const transactions: Transaction[] = [
  // Abril 2025
  {
    id: 1,
    date: "2025-04-01",
    description: "Venda de Produtos",
    amount: 5000,
    type: "income",
    category: "Vendas",
    client: "Empresa ABC Ltda",
    documentNumber: "NF-1234",
  },
  {
    id: 2,
    date: "2025-04-02",
    description: "Serviço de Consultoria",
    amount: 500,
    type: "income",
    category: "Serviços",
    client: "Cliente XYZ",
    documentNumber: "NF-1235",
  },
  {
    id: 3,
    date: "2025-04-05",
    description: "Aluguel do Escritório",
    amount: -1200,
    type: "expense",
    category: "Instalações",
    supplier: "Imobiliária Central",
    paymentMethod: "Transferência",
  },
  {
    id: 4,
    date: "2025-04-08",
    description: "Material de Escritório",
    amount: -450,
    type: "expense",
    category: "Suprimentos",
    supplier: "Papelaria Moderna",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 5,
    date: "2025-04-10",
    description: "Internet e Telefone",
    amount: -150,
    type: "expense",
    category: "Telecomunicações",
    supplier: "Telecom S.A.",
    paymentMethod: "Débito Automático",
  },
  {
    id: 6,
    date: "2025-04-12",
    description: "Energia Elétrica",
    amount: -250,
    type: "expense",
    category: "Utilidades",
    supplier: "Energia S.A.",
    paymentMethod: "Boleto",
  },
  {
    id: 7,
    date: "2025-04-15",
    description: "Venda de Serviços",
    amount: 1500,
    type: "income",
    category: "Serviços",
    client: "Empresa DEF",
    documentNumber: "NF-1236",
  },
  {
    id: 8,
    date: "2025-04-18",
    description: "Refeições Corporativas",
    amount: -120,
    type: "expense",
    category: "Alimentação",
    supplier: "Restaurante Executivo",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 9,
    date: "2025-04-20",
    description: "Combustível",
    amount: -200,
    type: "expense",
    category: "Transporte",
    supplier: "Posto Central",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 10,
    date: "2025-04-25",
    description: "Software de Gestão",
    amount: -150,
    type: "expense",
    category: "Software",
    supplier: "Tech Solutions",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 11,
    date: "2025-04-30",
    description: "Consultoria Prestada",
    amount: 2500,
    type: "income",
    category: "Serviços",
    client: "Cliente GHI",
    documentNumber: "NF-1237",
  },
  {
    id: 12,
    date: "2025-04-31",
    description: "Treinamento Equipe",
    amount: -180,
    type: "expense",
    category: "Treinamento",
    supplier: "Educorp Treinamentos",
    paymentMethod: "Transferência",
  },

  // Março 2025
  {
    id: 13,
    date: "2025-03-01",
    description: "Venda de Produtos",
    amount: 5000,
    type: "income",
    category: "Vendas",
    client: "Empresa JKL",
    documentNumber: "NF-1220",
  },
  {
    id: 14,
    date: "2025-03-05",
    description: "Aluguel do Escritório",
    amount: -1200,
    type: "expense",
    category: "Instalações",
    supplier: "Imobiliária Central",
    paymentMethod: "Transferência",
  },
  {
    id: 15,
    date: "2025-03-10",
    description: "Internet e Telefone",
    amount: -150,
    type: "expense",
    category: "Telecomunicações",
    supplier: "Telecom S.A.",
    paymentMethod: "Débito Automático",
  },
  {
    id: 16,
    date: "2025-03-12",
    description: "Energia Elétrica",
    amount: -230,
    type: "expense",
    category: "Utilidades",
    supplier: "Energia S.A.",
    paymentMethod: "Boleto",
  },
  {
    id: 17,
    date: "2025-03-15",
    description: "Projeto de Consultoria",
    amount: 3000,
    type: "income",
    category: "Serviços",
    client: "Empresa MNO",
    documentNumber: "NF-1221",
  },
  {
    id: 18,
    date: "2025-03-20",
    description: "Combustível",
    amount: -180,
    type: "expense",
    category: "Transporte",
    supplier: "Posto Central",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 19,
    date: "2025-03-25",
    description: "Material de Escritório",
    amount: -400,
    type: "expense",
    category: "Suprimentos",
    supplier: "Papelaria Moderna",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 20,
    date: "2025-03-31",
    description: "Jantar com Cliente",
    amount: -140,
    type: "expense",
    category: "Representação",
    supplier: "Restaurante Premium",
    paymentMethod: "Cartão Empresarial",
  },

  // Fevereiro 2025
  {
    id: 21,
    date: "2025-02-01",
    description: "Venda de Produtos",
    amount: 5000,
    type: "income",
    category: "Vendas",
    client: "Empresa PQR",
    documentNumber: "NF-1210",
  },
  {
    id: 22,
    date: "2025-02-05",
    description: "Aluguel do Escritório",
    amount: -1200,
    type: "expense",
    category: "Instalações",
    supplier: "Imobiliária Central",
    paymentMethod: "Transferência",
  },
  {
    id: 23,
    date: "2025-02-10",
    description: "Internet e Telefone",
    amount: -150,
    type: "expense",
    category: "Telecomunicações",
    supplier: "Telecom S.A.",
    paymentMethod: "Débito Automático",
  },
  {
    id: 24,
    date: "2025-02-12",
    description: "Energia Elétrica",
    amount: -210,
    type: "expense",
    category: "Utilidades",
    supplier: "Energia S.A.",
    paymentMethod: "Boleto",
  },
  {
    id: 25,
    date: "2025-02-18",
    description: "Serviço de Consultoria",
    amount: 2200,
    type: "income",
    category: "Serviços",
    client: "Empresa STU",
    documentNumber: "NF-1211",
  },
  {
    id: 26,
    date: "2025-02-22",
    description: "Combustível",
    amount: -170,
    type: "expense",
    category: "Transporte",
    supplier: "Posto Central",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 27,
    date: "2025-02-28",
    description: "Material de Escritório",
    amount: -370,
    type: "expense",
    category: "Suprimentos",
    supplier: "Papelaria Moderna",
    paymentMethod: "Cartão Empresarial",
  },

  // Janeiro 2025
  {
    id: 28,
    date: "2025-01-01",
    description: "Venda de Produtos",
    amount: 5000,
    type: "income",
    category: "Vendas",
    client: "Empresa VWX",
    documentNumber: "NF-1200",
  },
  {
    id: 29,
    date: "2025-01-05",
    description: "Aluguel do Escritório",
    amount: -1200,
    type: "expense",
    category: "Instalações",
    supplier: "Imobiliária Central",
    paymentMethod: "Transferência",
  },
  {
    id: 30,
    date: "2025-01-10",
    description: "Internet e Telefone",
    amount: -150,
    type: "expense",
    category: "Telecomunicações",
    supplier: "Telecom S.A.",
    paymentMethod: "Débito Automático",
  },
  {
    id: 31,
    date: "2025-01-12",
    description: "Energia Elétrica",
    amount: -240,
    type: "expense",
    category: "Utilidades",
    supplier: "Energia S.A.",
    paymentMethod: "Boleto",
  },
  {
    id: 32,
    date: "2025-01-20",
    description: "Projeto de Consultoria",
    amount: 2500,
    type: "income",
    category: "Serviços",
    client: "Empresa YZA",
    documentNumber: "NF-1201",
  },
  {
    id: 33,
    date: "2025-01-25",
    description: "Combustível",
    amount: -190,
    type: "expense",
    category: "Transporte",
    supplier: "Posto Central",
    paymentMethod: "Cartão Empresarial",
  },
  {
    id: 34,
    date: "2025-01-30",
    description: "Material de Escritório",
    amount: -420,
    type: "expense",
    category: "Suprimentos",
    supplier: "Papelaria Moderna",
    paymentMethod: "Cartão Empresarial",
  },
]

export const bills: Bill[] = [
  {
    id: 1,
    description: "Aluguel do Escritório",
    amount: 1200,
    dueDate: "2025-04-20",
    category: "Instalações",
    status: "pendente",
    account: "Conta Empresarial",
    recurrent: true,
    supplier: "Imobiliária Central",
    documentNumber: "Contrato 2023-45",
  },
  {
    id: 2,
    description: "Internet e Telefone",
    amount: 150,
    dueDate: "2025-04-15",
    category: "Telecomunicações",
    status: "pendente",
    account: "Conta Empresarial",
    recurrent: true,
    supplier: "Telecom S.A.",
    documentNumber: "Fatura 78901",
  },
  {
    id: 3,
    description: "Energia Elétrica",
    amount: 250,
    dueDate: "2025-04-18",
    category: "Utilidades",
    status: "pendente",
    account: "Conta Empresarial",
    recurrent: true,
    supplier: "Energia S.A.",
    documentNumber: "Fatura 56789",
  },
  {
    id: 4,
    description: "Água",
    amount: 100,
    dueDate: "2025-04-22",
    category: "Utilidades",
    status: "pendente",
    account: "Conta Empresarial",
    recurrent: true,
    supplier: "Água S.A.",
    documentNumber: "Fatura 12345",
  },
  {
    id: 5,
    description: "Parcela Equipamento",
    amount: 800,
    dueDate: "2025-04-10",
    category: "Equipamentos",
    status: "pago",
    account: "Conta Empresarial",
    recurrent: true,
    supplier: "Tech Solutions",
    documentNumber: "Contrato 2023-78",
  },
  {
    id: 6,
    description: "Serviço de Contabilidade",
    amount: 450,
    dueDate: "2025-04-25",
    category: "Serviços Profissionais",
    status: "pendente",
    account: "Cartão Empresarial",
    recurrent: true,
    supplier: "Contabilidade Express",
    documentNumber: "Contrato 2023-90",
  },
]

export const goals: Goal[] = [
  {
    id: 1,
    name: "Expansão de Mercado",
    target: 50000,
    current: 30000,
    deadline: "2025-07-15",
    department: "Comercial",
    responsible: "João Silva",
  },
  {
    id: 2,
    name: "Fundo de Reserva",
    target: 150000,
    current: 80000,
    deadline: "2025-12-31",
    department: "Financeiro",
    responsible: "Maria Oliveira",
  },
  {
    id: 3,
    name: "Aquisição de Equipamentos",
    target: 25000,
    current: 10000,
    deadline: "2025-09-30",
    department: "Operações",
    responsible: "Carlos Santos",
  },
  {
    id: 4,
    name: "Treinamento da Equipe",
    target: 15000,
    current: 5000,
    deadline: "2025-08-15",
    department: "RH",
    responsible: "Ana Pereira",
  },
]

// Função para formatar valores monetários
export const formatCurrency = (value: number) => {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(value)
}

// Calcular dias restantes
export const calculateDaysRemaining = (dateString: string) => {
  const dueDate = new Date(dateString)
  const today = new Date()
  const diffTime = dueDate.getTime() - today.getTime()
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24))
  return diffDays
}
